### Importación de datos

In [4]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

#1. Análisis de facturación

In [28]:
# Calcular la facturación (Precio + Costo de envío)
tienda['Facturación'] = tienda['Precio'] + tienda['Costo de envío']
tienda2['Facturación'] = tienda2['Precio'] + tienda2['Costo de envío']
tienda3['Facturación'] = tienda3['Precio'] + tienda3['Costo de envío']
tienda4['Facturación'] = tienda4['Precio'] + tienda4['Costo de envío']

# Agrupar por tienda (Lugar de Compra) y sumar la facturación
facturacion_por_tienda = tienda.groupby('Lugar de Compra')['Facturación'].sum().reset_index()
facturacion_por_tienda2 = tienda2.groupby('Lugar de Compra')['Facturación'].sum().reset_index()
facturacion_por_tienda3 = tienda3.groupby('Lugar de Compra')['Facturación'].sum().reset_index()
facturacion_por_tienda4 = tienda4.groupby('Lugar de Compra')['Facturación'].sum().reset_index()

In [29]:
# Mostrar resultados
print("Facturación total por tienda:\n")
print(facturacion_por_tienda)

print("Facturación total por tienda2:\n")
print(facturacion_por_tienda2)

print("Facturación total por tienda3:\n")
print(facturacion_por_tienda3)

print("Facturación total por tienda4:\n")
print(facturacion_por_tienda4)

Facturación total por tienda:

   Lugar de Compra  Facturación
0          Armenia    4858100.0
1     Barranquilla   34685800.0
2           Bogotá  463439800.0
3      Bucaramanga   18527400.0
4             Cali  162651900.0
5        Cartagena   23495800.0
6           Cúcuta   39926100.0
7          Inírida    2864800.0
8          Leticia   15452200.0
9        Manizales    8464700.0
10        Medellín  312738700.0
11           Neiva    3683100.0
12           Pasto   15803200.0
13         Pereira   59194000.0
14        Riohacha   19487000.0
15     Santa Marta   13921300.0
16          Soacha    4343100.0
17      Valledupar    1177600.0
18   Villavicencio    7543700.0
Facturación total por tienda2:

   Lugar de Compra  Facturación
0          Armenia    3541300.0
1     Barranquilla   29196800.0
2           Bogotá  505566300.0
3      Bucaramanga   25185400.0
4             Cali  124543000.0
5        Cartagena   22681000.0
6           Cúcuta   30544600.0
7          Inírida    2634400.0
8          Leticia   17020200.0
9        Manizales    3715100.0
10        Medellín  313107600.0
11           Neiva    4055600.0
12           Pasto   13474800.0
13         Pereira   45353300.0
14        Riohacha   13322900.0
15     Santa Marta   14574400.0
16          Soacha    2362200.0
17      Valledupar    1156000.0
18   Villavicencio    3793700.0
Facturación total por tienda3:

   Lugar de Compra  Facturación
0          Armenia    4186400.0
1     Barranquilla   38728200.0
2           Bogotá  500933100.0
3      Bucaramanga   24779400.0
4             Cali  115103000.0
5        Cartagena   35973600.0
6           Cúcuta   26490300.0
7          Inírida    1409000.0
8          Leticia   20248200.0
9        Manizales    6844200.0
10        Medellín  263922600.0
11           Neiva    4583800.0
12           Pasto    7161800.0
13         Pereira   65875200.0
14        Riohacha   20043100.0
15     Santa Marta   13516200.0
16          Soacha    2945000.0
17      Valledupar    2746000.0
18   Villavicencio    1047100.0
Facturación total por tienda4:

   Lugar de Compra  Facturación
0          Armenia     297400.0
1     Barranquilla   36464300.0
2           Bogotá  441649100.0
3      Bucaramanga   26930100.0
4             Cali  131142100.0
5        Cartagena   25704800.0
6           Cúcuta    7727200.0
7          Inírida    1607500.0
8          Leticia   18024400.0
9        Manizales    1366800.0
10        Medellín  265402900.0
11           Neiva    9683900.0
12           Pasto   15187800.0
13         Pereira   67505100.0
14        Riohacha   24959500.0
15     Santa Marta   13920200.0
16          Soacha    3328000.0
17      Valledupar    1115000.0
18   Villavicencio    1677000.0

# 2. Ventas por categoría

In [ ]:
ventas_por_categoria = tienda.groupby('Categoría del Producto')['Precio'].sum().reset_index().sort_values('Precio', ascending=False)
ventas_por_categoria2 = tienda2.groupby('Categoría del Producto')['Precio'].sum().reset_index().sort_values('Precio', ascending=False)
ventas_por_categoria3 = tienda3.groupby('Categoría del Producto')['Precio'].sum().reset_index().sort_values('Precio', ascending=False)
ventas_por_categoria4 = tienda4.groupby('Categoría del Producto')['Precio'].sum().reset_index().sort_values('Precio', ascending=False)

In [ ]:
print("Las ventas por categoría tienda 1: \n", ventas_por_categoria)
print("Las ventas por categoría tienda 2: \n", ventas_por_categoria2)
print("Las ventas por categoría tienda 3: \n", ventas_por_categoria3)
print("Las ventas por categoría tienda 4: \n", ventas_por_categoria4)

Las ventas por categoría tienda 1:
     Categoría del Producto       Precio
3             Electrónicos  429493500.0
2        Electrodomésticos  363685200.0
7                  Muebles  187633700.0
4   Instrumentos musicales   91299000.0
1     Deportes y diversión   39290000.0
5                 Juguetes   17995700.0
0  Artículos para el hogar   12698400.0
6                   Libros    8784900.0
Las ventas por categoría tienda 2:
     Categoría del Producto       Precio
3             Electrónicos  410831100.0
2        Electrodomésticos  348567800.0
7                  Muebles  176426300.0
4   Instrumentos musicales  104990300.0
1     Deportes y diversión   34744500.0
5                 Juguetes   15945400.0
0  Artículos para el hogar   14746900.0
6                   Libros   10091200.0
Las ventas por categoría tienda 3:
     Categoría del Producto       Precio
3             Electrónicos  410775800.0
2        Electrodomésticos  329237900.0
7                  Muebles  201072100.0
4   Instrumentos musicales   77380900.0
1     Deportes y diversión   35593100.0
5                 Juguetes   19401100.0
0  Artículos para el hogar   15060000.0
6                   Libros    9498700.0
Las ventas por categoría tienda 4:
     Categoría del Producto       Precio
3             Electrónicos  409476100.0
2        Electrodomésticos  283260200.0
7                  Muebles  192528900.0
4   Instrumentos musicales   75102400.0
1     Deportes y diversión   33350100.0
5                 Juguetes   20262200.0
0  Artículos para el hogar   15074500.0
6                   Libros    9321300.0

# 3. Calificación promedio de la tienda

In [16]:
# Calcular la calificación promedio
calificacion_promedio = tienda['Calificación'].mean()
calificacion_promedio2 = tienda2['Calificación'].mean()
calificacion_promedio3 = tienda3['Calificación'].mean()
calificacion_promedio4 = tienda4['Calificación'].mean()

In [18]:
#Mostrar resultado
print(f'La calificación promedio de la tienda es: {calificacion_promedio:.2f}')
print(f'La calificación promedio de la tienda 2 es: {calificacion_promedio2:.2f}')
print(f'La calificación promedio de la tienda 3 es: {calificacion_promedio3:.2f}')
print(f'La calificación promedio de la tienda 4 es: {calificacion_promedio4:.2f}')

La calificación promedio de la tienda es: 3.98
La calificación promedio de la tienda 2 es: 4.04
La calificación promedio de la tienda 3 es: 4.05
La calificación promedio de la tienda 4 es: 4.00

# 4. Productos más y menos vendidos

In [13]:
# Encontrar producto más y menos vendido por valor
producto_mas_vendido = tienda.loc[tienda['Precio'].idxmax()]
producto_menos_vendido = tienda.loc[tienda['Precio'].idxmin()]
# Encontrar producto más y menos vendido por valor
producto_mas_vendido2 = tienda2.loc[tienda['Precio'].idxmax()]
producto_menos_vendido2 = tienda2.loc[tienda['Precio'].idxmin()]
# Encontrar producto más y menos vendido por valor
producto_mas_vendido3 = tienda3.loc[tienda['Precio'].idxmax()]
producto_menos_vendido3 = tienda3.loc[tienda['Precio'].idxmin()]
# Encontrar producto más y menos vendido por valor
producto_mas_vendido4 = tienda4.loc[tienda['Precio'].idxmax()]
producto_menos_vendido4 = tienda4.loc[tienda['Precio'].idxmin()]

In [14]:
print("Producto más vendido en tienda 1 (por valor):")
print(f"Nombre: {producto_mas_vendido['Producto']}")
print(f"Categoría: {producto_mas_vendido['Categoría del Producto']}")
print(f"Precio: ${producto_mas_vendido['Precio']:,.2f}\n")

print("Producto menos vendido en tienda 1 (por valor):")
print(f"Nombre: {producto_menos_vendido['Producto']}")
print(f"Categoría: {producto_menos_vendido['Categoría del Producto']}")
print(f"Precio: ${producto_menos_vendido['Precio']:,.2f}\n")

print("Producto más vendido en tienda 2 (por valor):")
print(f"Nombre: {producto_mas_vendido2['Producto']}")
print(f"Categoría: {producto_mas_vendido2['Categoría del Producto']}")
print(f"Precio: ${producto_mas_vendido2['Precio']:,.2f}\n")

print("Producto menos vendido en tienda 2 (por valor):")
print(f"Nombre: {producto_menos_vendido2['Producto']}")
print(f"Categoría: {producto_menos_vendido2['Categoría del Producto']}")
print(f"Precio: ${producto_menos_vendido2['Precio']:,.2f}\n")

print("Producto más vendido en tienda 3 (por valor):")
print(f"Nombre: {producto_mas_vendido3['Producto']}")
print(f"Categoría: {producto_mas_vendido3['Categoría del Producto']}")
print(f"Precio: ${producto_mas_vendido3['Precio']:,.2f}\n")

print("Producto menos vendido en tienda 3 (por valor):")
print(f"Nombre: {producto_menos_vendido3['Producto']}")
print(f"Categoría: {producto_menos_vendido3['Categoría del Producto']}")
print(f"Precio: ${producto_menos_vendido3['Precio']:,.2f}\n")

print("Producto más vendido en tienda 4 (por valor):")
print(f"Nombre: {producto_mas_vendido4['Producto']}")
print(f"Categoría: {producto_mas_vendido4['Categoría del Producto']}")
print(f"Precio: ${producto_mas_vendido4['Precio']:,.2f}\n")

print("Producto menos vendido en tienda 4 (por valor):")
print(f"Nombre: {producto_menos_vendido4['Producto']}")
print(f"Categoría: {producto_menos_vendido4['Categoría del Producto']}")
print(f"Precio: ${producto_menos_vendido4['Precio']:,.2f}\n")

Producto más vendido en tienda 1 (por valor):
Nombre: TV LED UHD 4K
Categoría: Electrónicos
Precio: $2,977,000.00

Producto menos vendido en tienda 1 (por valor):
Nombre: Cubo mágico 8x8
Categoría: Juguetes
Precio: $7,600.00

Producto más vendido en tienda 2 (por valor):
Nombre: Smartwatch
Categoría: Electrónicos
Precio: $177,700.00

Producto menos vendido en tienda 2 (por valor):
Nombre: Bloques de construcción
Categoría: Juguetes
Precio: $31,600.00

Producto más vendido en tienda 3 (por valor):
Nombre: Ajedrez de madera
Categoría: Juguetes
Precio: $34,800.00

Producto menos vendido en tienda 3 (por valor):
Nombre: Olla de presión
Categoría: Artículos para el hogar
Precio: $72,100.00

Producto más vendido en tienda 4 (por valor):
Nombre: Mochila
Categoría: Deportes y diversión
Precio: $99,400.00

Producto menos vendido en tienda 4 (por valor):
Nombre: Secadora de ropa
Categoría: Electrodomésticos
Precio: $820,000.00

# 5. Envío promedio por tienda

In [19]:
# Calcular el envío promedio por tienda
envio_promedio_por_tienda = tienda.groupby('Lugar de Compra')['Costo de envío'].mean()
envio_promedio_por_tienda2 = tienda2.groupby('Lugar de Compra')['Costo de envío'].mean()
envio_promedio_por_tienda3 = tienda3.groupby('Lugar de Compra')['Costo de envío'].mean()
envio_promedio_por_tienda4 = tienda4.groupby('Lugar de Compra')['Costo de envío'].mean()

In [27]:
# Mostrar resultados
print("Envío promedio de tienda:\n")
print(envio_promedio_por_tienda)

# Mostrar resultados
print("Envío promedio de tienda2:\n")
print(envio_promedio_por_tienda2)

# Mostrar resultados
print("Envío promedio de tienda3:\n")
print(envio_promedio_por_tienda3)

# Mostrar resultados
print("Envío promedio de tienda4:\n")
print(envio_promedio_por_tienda4)

Envío promedio de tienda:

Lugar de Compra
Armenia          17314.285714
Barranquilla     23708.000000
Bogotá           23815.853659
Bucaramanga      30587.096774
Cali             28827.561837
Cartagena        22624.528302
Cúcuta           40129.411765
Inírida          28460.000000
Leticia          24450.000000
Manizales        29140.000000
Medellín         28207.104796
Neiva            31516.666667
Pasto            35078.260870
Pereira          22403.759398
Riohacha         24357.500000
Santa Marta      22593.750000
Soacha           43420.000000
Valledupar       18766.666667
Villavicencio    34709.090909
Name: Costo de envío, dtype: float64
Envío promedio de tienda2:

Lugar de Compra
Armenia          44525.000000
Barranquilla     18660.256410
Bogotá           25997.055838
Bucaramanga      25796.000000
Cali             28312.612613
Cartagena        16181.428571
Cúcuta           26323.728814
Inírida          64900.000000
Leticia          25329.411765
Manizales        13476.923077
Medellín         26701.851852
Neiva            36033.333333
Pasto            26988.000000
Pereira          17808.593750
Riohacha         19042.857143
Santa Marta      18627.500000
Soacha           30375.000000
Valledupar       14050.000000
Villavicencio    32766.666667
Name: Costo de envío, dtype: float64
Envío promedio de tienda3:

Lugar de Compra
Armenia          29442.857143
Barranquilla     25450.649351
Bogotá           25809.766022
Bucaramanga      24810.000000
Cali             23449.193548
Cartagena        32669.642857
Cúcuta           30109.090909
Inírida          18825.000000
Leticia          25253.658537
Manizales        48914.285714
Medellín         23003.448276
Neiva            22430.000000
Pasto            22531.250000
Pereira          25154.477612
Riohacha         23118.181818
Santa Marta      15043.181818
Soacha           23833.333333
Valledupar       45933.333333
Villavicencio    11820.000000
Name: Costo de envío, dtype: float64
Envío promedio de tienda4:

Lugar de Compra
Armenia           4566.666667
Barranquilla     23016.250000
Bogotá           22519.778002
Bucaramanga      27410.000000
Cali             26200.393701
Cartagena        20907.936508
Cúcuta           12331.250000
Inírida          26800.000000
Leticia          26174.285714
Manizales        11366.666667
Medellín         23256.672444
Neiva            26600.000000
Pasto            25710.000000
Pereira          27626.229508
Riohacha         28972.727273
Santa Marta      20045.714286
Soacha           44750.000000
Valledupar       14500.000000
Villavicencio    12914.285714
Name: Costo de envío, dtype: float64